finish oam model chinese doc
kubevela/kubevela.github.io pull request #147
Opened 2021-08-06 11:10 UTC by wonderflow

2021-08-10 07:09 UTC, BinaryHB0916 approved these changes
LGTM

2021-08-10 07:11 UTC, BinaryHB0916 requested changes
X- Definition 的部分，需要完成剩下的中文化。

2021-08-10 09:13 UTC, BinaryHB0916 approved these changes
我这里没有问题了。看看磊哥还有没有 comment。

2021-08-10 23:32 UTC, resouer reviewed
Review comment part 1

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +KubeVela 的交付模型是 OAM（Open Application Model）。OAM 模型主要的优势是原生可扩展，它把应用交付的各个组件和能力原子被抽象成原子化、可被复用的“乐高模块”：
```suggestion
KubeVela 背后的应用交付模型是 OAM（Open Application Model），即：开放应用模型。开放应用模型允许用户把一个现代微服务应用部署所需的所有组件和各项运维动作，描述为一个统一的、与基础设施无关的“部署计划”（这个过程称作“建模”），进而实现在混合环境中进行标准化和高效率的应用交付。具体来说：
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +* 每一个单个乐高模块都是高度内聚的，用户可以很容易知道应该如何使用这个模块。
不要写一堆技术原理，要说清楚怎么用，作用是什么。

```suggestion
* 用户通过一个叫做应用部署计划（Application）的对象来声明一个微服务应用的完整交付流程，这其中包含了待交付组件、关联的运维动作、交付流水线等内容。
* 所有的待交付组件、运维动作和流水线中的每一个步骤，都遵循 OAM 规范设计为独立的可插拔模块，允许用户按照自己的需求进行组合或者定制。
* OAM 模型也会负责规范各个模块之间的协作接口。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +![oam-model](../../resources/oam-model.png)
这个图没有翻译完全。其中右下角那个 workflow 的框应该叫“部署的执行过程”

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +**Application** 对象是 KubeVela 的核心 API，它表达了一个应用的完整部署计划。最终用户只需要描述这样一个 Application 文件，就可以涵盖应用交付的所有组件和部署策略。
```suggestion
**Application** 对象是用户唯一需要了解的 API，它表达了一个微服务应用的部署计划。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +OAM 模型将一次应用部署计划（Application）拆解为“待部署组件（Component）”、“运维能力（Trait）”、“应用的执行策略（Policy）”，以及“部署执行方式工作流（Workflow）”这四部分概念组成。每个概念里面都可以包含可插拔和扩展的多个模块，就像乐高积木一样可以自由组合，从而满足不同的场景和诉求。
```suggestion
遵循 OAM 规范，一个应用部署计划（Application）由“待部署组件（Component）”、“运维动作（Trait）”、“应用的执行策略（Policy）”，以及“部署工作流（Workflow）”这四部分概念组成。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +对于最终用户而言，学习和使用 Application 就是他们需要了解 OAM 的全部内容，不再需要了解其他基础设施层的细节。以图中描述的组件为例，用户要部署一个带有公网流量访问的常驻进程服务，可以通过申明使用“webservice”这个组件类型来实现，不再需要了解底层的 Kubernetes 细节是由什么资源构成的。同样的，云资源也可以用类似的方式描述和部署。
v1.1 的整体文档必须以 Helm chart 为例子，而不是 webservice worker 这些。

```suggestion
而无论待交付的组件是 Helm chart 还是云数据库、目标基础设施是 Kubernetes 集群还是云平台，KubeVela 都通过 Application 这样一个统一的、上层的交付描述文件来同用户交互，不会泄露任何复杂的底层基础设施细节，真正做到让用户完全专注于应用研发和交付本身。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +其中组件类型、运维特征类型、应用策略类型、以及工作流节点类型，都是平台预先定义好、并且可以扩展的，这些统称为 [模块定义（X-Definition）](./x-definition)。所有的参数的字段数量和类型均是由具体的模块定义决定的，也就是说一个应用交付的参数类型是由实际选择了具体的类型以后确定的。所以整个 Application 对象并没有固定的字段格式，它是由多个“可编程模块”组合而成的
```suggestion
在实际使用时，用户通过上述 Application 对象来引用预置的组件、运维特征、应用策略、以及工作流节点模块，填写这些模块暴露的用户参数即可完成一次对应用交付的建模。

> 注意：上诉可插拔模块在 OAM 中称为 X-Definitions，Application 对象负责引用 X-Definitions 并对用户输入进行校验，而各模块具体的可填写参数则是约束在相应的 X-Definition 文件当中的。具体请参考： [模块定义（X-Definition）](./x-definition) 章节。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +待部署组件（Component）是构成完整应用的微服务单元，比如一个 WordPress 应用包含 WordPress 程序主体以及 MySQL 数据库两个组件。
Workdpress 并不是一个典型的微服务应用，这个常识要有。


```suggestion
组件（Component）是构成微服务应用的基本单元，比如一个 [Bookinfo](https://istio.io/latest/docs/examples/bookinfo/) 应用可以包含 Ratings、Reviews、Details 等多个组件。
```

2021-08-10 23:32 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +KubeVela 默认会安装一些可以开箱即用的组件类型，如微服务组件、短时任务组件等。除此之外，平台管理员可以非常方便的扩展和自定义组件类别。这里的组件类别可以是无状态服务、有状态中间件、各类云服务、一次性任务等等；组件的制品形态可以是 Helm Chart、容器镜像、各类 IaC 格式配置文件等。KubeVela 的交付能力基本涵盖了所有云原生组件的部署需求。
```suggestion
KubeVela 内置即支持多种类型的组件交付，包括 Helm Chart、容器镜像、CUE 模块、Terraform 模块等等。同时，KubeVela 也允许平台管理员以 CUE 语言的形式增加其它任意类型的组件。
```

2021-08-11 06:26 UTC, resouer reviewed
Part 2 comment 了，Done

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +* 乐高模块之间的衔接有固定的凹槽和标准。意味着抽象后的模块化能力有标准化的衔接方式，如固定的输入、输出参数和类型；是否适配和冲突有明确的标识。
10-12 不要了，太细节

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +运维特征（Trait）是组件部署完成以后对组件持续生命周期管理的运维能力，包括服务发布、访问、治理、弹性、可观测性、灰度发布等运维策略。
```suggestion
运维特征（Trait）负责定义组件可以关联的通用运维行为，比如服务发布、访问、治理、弹性、可观测性、灰度发布等。在 OAM 规范中，一个组件可以绑定任意个运维特征。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +KubeVela 默认会安装一些可以开箱即用的运维特征，如灰度发布、标签管理、配置管理、弹性扩缩容等。除此之外，平台管理员可以非常方便的扩展和自定义运维类别。这里的运维特征可以是应用生命周期涉及到的所有方面，比如流量管理、安全扫描、日志监控、暂停重启等等。KubeVela 可以灵活的扩展和对接所有云原生的运维特征。
```suggestion
与组件系统的可扩展性类似，KubeVela 允许平台管理员在系统中随时增加新的运维特征。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +应用的执行策略（Policy）是应用整体性的特征，包括健康检查、安全组、防火墙、SLO、检验等模块。
```suggestion
应用的执行策略（Policy）负责定义应用级别的部署特征，比如健康检查规则、安全组、防火墙、SLO、检验等模块。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +应用执行策略的扩展性和功能与运维特征类似，可以灵活的扩展和对接所有云原生应用生命周期管理的能力。相对于运维特征而言，应用执行策略偏向于一个应用的整体，而运维特征偏向于应用中的某个组件。
```suggestion
应用执行策略的扩展性和功能与运维特征类似，可以灵活的扩展和对接所有云原生应用生命周期管理的能力。相对于运维特征而言，应用执行策略作用于一个应用的整体，而运维特征作用于应用中的某个组件。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +部署执行工作流是达到应用终态的路径，允许用户自定义应用部署的执行方式，如多环境、多集群部署，自定义组件依赖和部署顺序，运行时数据传递等等。默认情况下用户不需要自定义工作流，会自动按照组件和运维特征数组的顺序依次部署到当前集群。
```suggestion
部署执行工作流（Workflow）定义了从部署开始到达到部署终态的一条完整路径，KubeVela 会按这个流水线执行工作流中定义的各个步骤来完成整个应用交付。除了常规的组件依赖编排、数据流传递等功能，KubeVela 的工作流还支持面向多环境/多集群的部署过程与策略描述。

> 注意：如果用户没有定义工作流，KubeVela 默认会自动按照组件和运维特征数组的顺序进行部署，并把 KubeVela 所在的当前集群作为目标集群。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +默认情况下 KubeVela 包含了诸如创建资源、条件判断、数据输入输出等工作流节点，除此之外用户也可以自定义工作流节点的功能，组装衔接出一些复杂场景，诸如集群创建、应用部署、状态通知、多环境部署等流程。
```suggestion
KubeVela 当前内置的工作流步骤节点包括了创建资源、条件判断、数据输入输出等。同组件等系统类似，KubeVela 所支持的工作流节点也允许平台管理员自行定义和扩展。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +## 配置一致性
```suggestion
## 避免配置漂移
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +KubeVela 通过类似 IaC (Infrastructure-as-Code) 的理念来保证组件的高效、可扩展，但是通常 IaC 工具会引入应用配置状态不一致的问题，比如配置中心的配置和生产环境实际状态不一致等，这个问题就是所谓的“配置漂移”（Infrastructure/Configuration Drift）。
```suggestion
在具体实现上，KubeVela 采用了脱胎于 Google Borg 系统的 [CUE 配置语言](https://cuelang.org/) 作为模型层实现，从而以 IaC (Infrastructure-as-Code) 的方式实现了 OAM 各个模块之间的高效协作和灵活扩展。但另一方面，常规的 IaC 技术往往会引入“配置漂移”（Infrastructure/Configuration Drift）的问题，即：当用户声明的应用部署配置和生产环境实际运行的实例状态发生不一致时，IaC 就无能为力了。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +所以 KubeVela 在管理这些可编程模块的过程中，引入了 [Kubernetes 控制循环](https://kubernetes.io/docs/concepts/architecture/controller/) 的机制，通过 Kubernetes 的控制循环，保证配置和终态的一致，以此防止配置漂移的发生，同时依旧保证了模块的灵活性和可扩展能力。
```suggestion
所以 KubeVela 在采用 IaC 技术实现的同时，还同时通过 [Kubernetes 控制循环](https://kubernetes.io/docs/concepts/architecture/controller/) 来管控整个 IaC 模型的渲染和执行，从而以完全自动化的方式保证了应用配置和终态的一致性，同时在模块定义、封装、扩展过程中保留了完整的 IaC 的使用体验。简介明了的 CUE 模板语法是平台管理员自行扩展 KubeVela 时唯一需要学习的一项技术。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +模块化定义的实例，是具体的各种功能类型，KubeVela 内置的组件类型，如 webservice 就是组件定义的一种模块化定义实例。KubeVela 的系统管理员，也就是平台工程师或 DevOps 工程师，可以非常容易的通过编写和注册模块化定义的实例，来扩展 KubeVela 系统支持的功能类型。
这句不要。

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +模块定义（X-Definition）是所有模块化能力的代称，目前主要包括组件定义（ComponentDefinition），运维特征定义（TraitDefinition）、应用策略定义（PolicyDefinition），工作流节点定义（WorkflowStepDefinition）等，随着系统演进，OAM 模型未来可以根据场景需要增加模块化定义概念。
```suggestion
当前 OAM 模型支持的模块定义（X-Definition）包括组件定义（ComponentDefinition），运维特征定义（TraitDefinition）、应用策略定义（PolicyDefinition），工作流节点定义（WorkflowStepDefinition）等，随着系统演进，OAM 模型未来可能会根据场景需要进一步增加新的模块定义。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +设计组件定义（ComponentDefinition）的目标就是允许平台的管理员可以将不同的可部署制品类型通过 OAM 模型的，用统一的方式抽象出来。这个可部署制品类型不同格式的制品文件本身及其对应的部署方式。抽象后的组件定义使得用户可以在部署计划（Application）中作为一个组件类型非常容易的配置和使用。
```suggestion
组件定义（ComponentDefinition）的设计目标是允许平台管理员将任何类型的可部署制品封装成待交付的“组件”。只要定义好之后，这种类型的组件就可以被用户在部署计划（Application）中引用、实例化并交付出去。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +一个组件定义就代表了一类组件的提供形式，组件的提供形式可以是多种多样的，常见的比如 Helm Chart 、Kubernetes YAML文件、镜像、云资源 IaC 文件、或者 CUE 配置文件模块等等。组件供应方对应真实世界中的角色，一般就是第三方软件的分发者（ISV）、DevOps 团队的工程师、或者你自己建设的 CI 体系生成的代码包和镜像。
```suggestion
常见的组件类型包括 Helm Chart 、Kustomize 目录、一组 Kubernetes YAML文件、容器镜像、云资源 IaC 文件、或者 CUE 配置文件模块等等。组件供应方对应真实世界中的角色，一般就是第三方软件的分发者（ISV）、DevOps 团队的工程师、或者你自己建设的 CI 体系生成的代码包和镜像。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +  workload: # 工作负载类型
```suggestion
  workload: # 工作负载描述
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +  schematic:  # 抽象方式
```suggestion
  schematic:  # 组件描述
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +    cue: # 存在多种抽象方式
```suggestion
    cue: # 通过 CUE 语言定义的组件详情
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +除了基本的“组件定义名称”和“功能描述说明”以外，组件定义的核心是 `.spec` 下面的两部分，一部分是工作负载类型；另一部分是抽象方式。
```suggestion
除了基本的“组件定义名称”和“功能描述说明”以外，组件定义的核心是 `.spec` 下面的两部分，一部分是工作负载类型；另一部分是组件描述。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +* 工作负载类型（对应`.spec.workload`）字段，指的是一个组件背后对应的工作负载。它有两种写法，一种如例子中显示的，填写 `.spec.workload.definition` 的具体资源组和资源类型名称。另一种方法则是填写一个工作负载类型的名称。
```suggestion
* 工作负载类型（对应`.spec.workload`）字段为系统指明了一个组件背后对应的工作负载类型。它有两种定义方式，一种如例子中显示的，填写 `.spec.workload.definition` 的具体资源组和资源类型名称。另一种方法则是填写一个工作负载类型的名称。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +* 抽象方式（对应`.spec.schematic`）字段，指的是一个组件的抽象方式和交付方式。目前主要有 [`cue`](../cue/basic) 和 [`kube`](../kube/component) 两种抽象方式。
```suggestion
* 组件描述（对应`.spec.schematic`）定义了组件的详细信息。该部分目前支持 [`cue`](../cue/basic) 和 [`kube`](../kube/component) 两种描述方式。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +具体抽象方式和交付方式的编写可以查阅对应的文档，这里以一个完整的例子介绍组件定义的工作流程。
下面这个例子改成 Helm 组件。不要举一些无意义的例子，出现在文档中的所有例子一律会被用户视作最佳实践。

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +顾名思义，运维特征定义（TraitDefinition）为应用提供了一系列运维能力的模块，这些运维能力通常都是由平台管理员提供的。运维特征附着于一个具体的组件，为这个组件提供一系列的运维操作和策略，比如添加一个负载均衡策略、路由策略、弹性扩缩容、灰度发布策略等等。
```suggestion
运维特征定义（TraitDefinition）为组件提供了一系列可被按需绑定的运维动作，这些运维动作通常都是由平台管理员提供的运维能力，它们为这个组件提供一系列的运维操作和策略，比如添加一个负载均衡策略、路由策略、或者执行弹性扩缩容、灰度发布策略等等。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +* 抽象方式（对应`.spec.schematic`）字段，指的是一个组件的抽象方式和交付方式。目前主要通过 [`CUE`](../traits/trait) 来实现，同时也包含一系列诸如[`patch-trait`](../traits/advanced.md)这样的高级用法。
```suggestion
* 特征描述（对应`.spec.schematic`）字段定义了具体的运维动作。目前主要通过 [`CUE`](../traits/trait) 来实现，同时也包含一系列诸如[`patch-trait`](../traits/advanced.md)这样的高级用法。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +应用策略定义与运维特征定义类似，区别在于运维特征是针对组件的，而应用策略是针对整个应用整体的。它可以为应用提供全局的管理，常见的包括全局安全策略（如 RBAC权限、审计、秘钥管理）、应用洞察（如 应用的 SLO 管理等）。
```suggestion
应用策略定义与运维特征定义类似，区别在于运维特征作用于单个组件，而应用策略是作用于整个应用整体（多个组件）。它可以为应用提供全局的策略定义，常见的包括全局安全策略（如 RBAC权限、审计、秘钥管理）、应用洞察（如 应用的 SLO 管理等）。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +  schematic:  # 抽象方式
```suggestion
  schematic:  # 策略描述
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +主要介绍其中的抽象部分，基于 CUE 格式，输出一个 `EnvBinding` 对象，其参数就是 engine 和 envs 两个，其中 envs 是一个结构体数组，具体的结构体类型和其中的参数由 `#Env` 指定，这里面的 CUE 语法与[组件定义的 CUE 语法](../cue/basic.md)一致。
```suggestion
主要介绍其中的策略描述部分，基于 CUE 格式，输出一个 `EnvBinding` 对象，其参数就是 engine 和 envs 两个，其中 envs 是一个结构体数组，具体的结构体类型和其中的参数由 `#Env` 指定，这里面的 CUE 语法与[组件定义的 CUE 语法](../cue/basic.md)一致。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +工作流节点定义用于描述一系列工作流中可以使用的节点类型，如执行资源的部署、状态检查、数据输出、依赖输入、外部脚本调用等一系列能力均可以通过工作流节点定义来描述。
```suggestion
工作流节点定义用于描述一系列在工作流中可以声明的步骤节点，如执行资源的部署、状态检查、数据输出、依赖输入、外部脚本调用等一系列能力均可以通过工作流节点定义来描述。
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +  schematic:  # 抽象方式
```suggestion
  schematic:  # 节点描述
```

2021-08-11 06:26 UTC, resouer commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +工作负载定义（WorkloadDefinition）用于定义 Kubernetes 系统中实际资源的特征，可以作为元数据被 OAM 系统中的其他概念的扩展插件所查询和使用，同时也可以作为组件定义的约束条件，定义组件定义时系统中必须要存在工作负载定义，以此来避免某些不该开放的工作负载被定义为组件类型。
```suggestion
工作负载定义（WorkloadDefinition）是组件的一种系统级特征，它不是用户所关心的字段，而是作为元数据被 OAM 系统本身进行检查、验证和使用。
```

2021-08-11 07:54 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/oam-model.md
> +* 用户通过一个叫做应用部署计划（Application）的声明式对象来进行选择和组装这些模块。
```suggestion
```

2021-08-11 08:08 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/oam/x-definition.md
> +模块化定义的实例，是具体的各种功能类型，KubeVela 内置的组件类型，如 webservice 就是组件定义的一种模块化定义实例。KubeVela 的系统管理员，也就是平台工程师或 DevOps 工程师，可以非常容易的通过编写和注册模块化定义的实例，来扩展 KubeVela 系统支持的功能类型。
```suggestion
```

2021-08-11 08:28 UTC, merged