add addon doc
kubevela/kubevela.github.io pull request #164
Opened 2021-08-13 14:09 UTC by chivalryq

2021-08-16 07:01 UTC, BinaryHB0916 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +KubeVela 可以利用CUE的强大能力集成 Kubernetes 生态中的其他组件，例如：Fluxcd、Keda、Prometheus 等。插件系统提供了一种统一的方式安装这些组件，且提供了一些开箱即用的 X-Definition。
CUE、Fluxcd、addon 的这些中英文，辛苦加下半角空格

2021-08-16 07:31 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
这块文档应该有2部分，一部分是 end user 怎么查看已有的addon，怎么安装，怎么看安装是不是成功；另一部分是 platform builder 怎么添加一个addon。

2021-08-16 08:11 UTC, BinaryHB0916 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +FLuxcd 中已经附带了一个帮助交付 helm chart 类型的[组件定义](https://github.com/oam-dev/kubevela/blob/master/vela-templates/addons/fluxcd/definitions/helm-release.yaml) helm：
FLuxcd 捉虫

2021-08-16 08:30 UTC, BinaryHB0916 requested changes
整体特别棒的，再优化一下：
1、从第三步那里开始改写。要站在用户的的视角，以类似“假设你需要给用户提供一个自定义的 Redis，那如何通过 addon 来达成的这个需求”开头进行描述；
2、demo 的时候，所有命令行的返回也要贴出来的，让用户有预期正确的结果是什么样的，比如：
```
kubectl apply -f addon-app.yaml
application.core.oam.dev/app-delivering-chart created
```

谢谢。 @wonderflow 天元也可以再看一下～

2021-08-16 08:36 UTC, BinaryHB0916 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
vela addon 给 end user 开放，看起还来不完备。比如说通过 fluxcd 可以集成哪些已有的自定义组件，vela show 等相关命令行还没有跟上。

2021-08-17 09:14 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
我理解addon的启用职责应当交给platform builder吧？

2021-08-17 09:51 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
> 这块文档应该有2部分，一部分是 end user 怎么查看已有的addon，怎么安装，怎么看安装是不是成功；另一部分是 platform builder 怎么添加一个addon。

这个目前来看不具备让用户来写的条件，可能platform builder目前去写一个addon意义不大，不如直接写definition。

而且我们最好给一个分享的平台，让社区用户产生内容，这才具备基本的platform builder写addon的条件吧

2021-08-17 10:08 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
嗯，现在这样可以，给platform builder 看，但是 end user 可以ref 文档过来

2021-08-17 10:59 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +本节会介绍：如何使用 KubeVela 的 addon（插件）能力
```suggestion
本节会介绍如何使用 KubeVela 的默认系统插件（Addon），以及如何添加一个系统插件。
```

2021-08-17 11:09 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +KubeVela 可以利用 CUE 的强大能力集成 Kubernetes 生态中的其他组件，例如：Fluxcd、Keda、Prometheus 等。插件系统提供了一种统一的方式安装这些组件，且提供了一些开箱即用的 X-Definition。
```suggestion
KubeVela 默认是一个应用管理和交付的控制平面，同时它也支持一系列开箱即用的功能，这些都通过系统插件的方式提供。系统管理员只需要一键即可开启这些默认的系统插件，使用包括弹性扩缩容、可观测性、GitOps 在内的多种生态功能。

除此之外，系统管理员也可以将系统插件交由用户使用，同时根据需要添加自定义的系统插件。本质上，系统插件提供了一种统一的方式，可以灵活的安装、拆卸满足应用交付和应用管理不同场景的系统能力。

一个系统插件通常可以包含如下几个组成部分：

- 系统组件，如 Kubernetes 的自定义资源（CRD Controller），系统所需的数据库、缓存、负载均衡等中间件，其他容易需要安装运行的系统组件。
- OAM 标准化定义（X-Definition），如组件定义（ComponentDefinition）等，可以将系统组件的能力通过 OAM 的标准方式提供给最终的用户使用。
```

2021-08-17 11:13 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +确保你已经安装了 [vela CLI](../install.mdx)
```suggestion
系统插件可以通过 KubeVela 的命令行工具一键安装，请确保你已经安装了 [vela CLI](../install.mdx)。
```

2021-08-17 11:14 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +## 如何使用
```suggestion
## 查看默认的系统插件
```

2021-08-17 11:15 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +下面将以 Fluxcd 为例，演示一个插件的安装和使用过程。
这部分挪到下面

2021-08-17 11:15 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +2. 使用 vela CLI 查看可用的插件
```suggestion
1. 使用 vela CLI 查看系统默认的插件。
```

2021-08-17 11:16 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +
2. 系统插件介绍

搞个表格依次用中文介绍一下是做什么的。

2021-08-17 11:17 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +3. 启用 Fluxcd, CLI 将会持续检查 Fluxcd 插件的状态，直至其成功安装。
```suggestion
3. 以 fluxcd 这个插件为例，启用 fluxcd 以后, CLI 将会持续检查 fluxcd 插件的状态，直至其成功安装。
```

这里用小写 fluxcd 是指代你的输出。 如果你要提的是FluxCD 官网，或者这个项目，就得按标准的方式，注意大小写。

2021-08-17 11:18 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +或者使用vela CLI
这部分不要，直接介绍 vela components 命令即可

2021-08-17 11:19 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
这里有个 vela show 命令可以用。cue写成文档没人看得懂

2021-08-17 11:20 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
这个部分应该放到 fluxcd 这个addon专门的介绍里面。

2021-08-17 11:20 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +## 插件背后
```suggestion
## 如何添加一个自定义系统插件
```

这里要完整的介绍怎么加一个系统插件。

2021-08-17 11:22 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
这部分只需要介绍到 fluxcd addon 装完以后可以通过 vela components 看到 新出现了一个组件即可。剩下的应该重新开个子文档专门介绍 fluxcd 这个系统插件。对应的其他系统插件也需要这么介绍。

2021-08-17 11:41 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +FLuxcd 中已经附带了一个帮助交付 helm chart 类型的[组件定义](https://github.com/oam-dev/kubevela/blob/master/vela-templates/addons/fluxcd/definitions/helm-release.yaml) helm：
done

2021-08-17 12:45 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +```
等流鑫把vela show修复

2021-08-17 12:48 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +
done

2021-08-17 12:48 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +3. 启用 Fluxcd, CLI 将会持续检查 Fluxcd 插件的状态，直至其成功安装。
done

2021-08-17 12:49 UTC, chivalryq commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +## 插件背后
等待 https://github.com/oam-dev/kubevela/issues/2112 就绪

2021-08-19 02:18 UTC, BinaryHB0916 approved these changes
Approve，看下 CI。

2021-08-19 05:48 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/end-user/components/helm.md
> +## 示例
```suggestion
## 部署来自 Helm 仓库的 Chart
...

## 部署来自 OSS 存储的 Chart

...

## 部署来自 Git 服务的 Chart
```

2021-08-19 07:29 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon.md
> +## 插件背后
这里标题还是要改掉的，然后在最后加一句话，添加自定义系统插件的教程将在近期完善，敬请期待

2021-08-19 07:46 UTC, wonderflow approved these changes

2021-08-19 07:46 UTC, merged