translate i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
kubevela/kubevela.github.io pull request #26
Opened 2021-04-09 09:25 UTC by lxd5866

translate i18n/zh/docusaurus-plugin-content-docs/current/introduction.md

2021-04-12 01:56 UTC, sunny0826 requested changes

2021-04-12 01:56 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +云原生技术正在以Kubernetes作为通用抽象层，朝着跨云追求一致的应用交付迈进。 Kubernetes虽然在抽象底层基础结构细节方面表现出色，也为应用程序开发人员带来了额外的复杂性， 需要了解Pod，端口暴露，特权提升，资源声明，CRD等概念。 我们看到了陡峭的学习曲线，缺乏面向开发人员的抽象影响了用户体验，降低了生产率， 导致了生产中的意外错误或配置错误。人们开始质疑这场革命的价值：“我为
中英文之间请使用空格隔开

2021-04-12 01:56 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +最大的区别在于 **灵活性**。
中文和中文之间不需要使用空格

2021-04-12 01:56 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +现在，让我们 [开始](./quick-start.md) 使用KubeVela！
链接格式同上

2021-04-12 09:59 UTC, lxd5866 commented
@sunny0826 resolved

2021-04-15 05:49 UTC, wonderflow reviewed
请根据翻译规则更新一下

2021-04-28 06:19 UTC, lxd5866 commented
opinionated 不确定怎么翻译，有自以为是，自用，武断的意思，但感觉都不太对，需要帮忙看一下

2021-04-30 02:03 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +另一方面，抽象 Kubernetes 来满足开发人员的需求是一个非常 opinionated 的过程，只有在决策者是平台构建者的情况下，最终的抽象才有意义。不幸的是，当今的平台构建者面临以下难题：
```suggestion
另一方面，抽象 Kubernetes 来满足开发人员的需求是一个非常依赖经验判断的过程，只有在决策者是平台构建者的情况下，最终的抽象才有意义。不幸的是，当今的平台构建者面临以下难题：
```

2021-04-30 02:04 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +最终结果是，开发人员抱怨这些平台过于僵化，响应功能要求或改进速度太慢。平台建设者确实希望提供帮助，但是工程上的努力却是艰巨的：平台中任何简单的 API 更改都可能很容易成为围绕 opinionated 抽象设计的马拉松式谈判。
```suggestion
最终结果是，开发人员抱怨这些平台过于僵化，响应功能要求或改进速度太慢。平台建设者确实希望提供帮助，但是工程上的努力却是艰巨的：平台中任何简单的 API 更改都可能很容易成为围绕经验主义进行抽象设计的马拉松式谈判。
```

2021-05-10 03:27 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +云原生技术正在以 Kubernetes 作为通用抽象层，朝着跨云追求一致的应用交付迈进。Kubernetes 虽然在底层基础结构细节抽象方面表现出色，但带来了额外的复杂性，应用程序开发人员需要了解 pods, port exposing, privilege escalation, resource claims, CRD 等概念。我们看到了陡峭的学习曲线，缺乏面向开发人员的抽象影响了用户体验，
```suggestion
云原生技术正在以 Kubernetes 作为通用抽象层，朝着跨云追求一致的应用交付迈进。Kubernetes 虽然在底层基础结构细节抽象方面表现出色，但带来了额外的复杂性，应用程序开发人员需要了解 Pod、端口暴露、权限、资源声明和管理、 CRD 等概念。我们看到了陡峭的学习曲线，缺乏面向开发人员的抽象影响了用户体验，降低了生产率，导致了生产中的意外错误或配置错误。人们开始质疑这场革命的价值：“我为什么要烦恼所有这些细节？”。
```

2021-05-10 03:30 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +- 简单而可靠的抽象机制。与大多数 IaC(基础设施即代码)解决方案不同，KubeVela 中的抽象是用 [Kubernetes Control Loop](https://kubernetes.io/docs/concepts/architecture/controller/) 构建的，所以它们永远不会在集群中留下配置漂移。作为 [Kubernetes 自定义资源](https://kuber
```suggestion
- 简单而可靠的抽象机制。与大多数 IaC(基础设施即代码)解决方案不同，KubeVela 中的抽象是用 [Kubernetes Control Loop](https://kubernetes.io/docs/concepts/architecture/controller/) 构建的，所以它们永远不会在集群中留下配置漂移。作为 [Kubernetes 自定义资源](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/)，KubeVela可以与任何 CI/CD 或 GitOps 工具无缝协作，不需要进行集成工作。
```

2021-05-10 03:31 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/introduction.md
> +KubeVela 是一个 Kubernetes 插件，用于构建更高级别的抽象。它利用 [Open Application Model](https://github.com/oam-dev/spec) 和本地 Kubernetes 的可扩展性来解决一个困难的问题 —让在 Kubernetes 上发布应用程序变得愉快。
```suggestion
KubeVela 是一个 Kubernetes 插件，用于构建更高级别的抽象。它利用 [Open Application Model](https://github.com/oam-dev/spec) 和本地 Kubernetes 的可扩展性来解决一个困难的问题 -- 让在 Kubernetes 上发布应用程序变得愉快。
```

2021-05-12 11:10 UTC, wonderflow approved these changes

2021-05-12 12:01 UTC, merged