translate i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
kubevela/kubevela.github.io pull request #46
Opened 2021-04-17 08:36 UTC by Casper-Mars

translate i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md

2021-04-19 01:34 UTC, sunny0826 requested changes
总体翻译流畅，有部分不通顺的地方请修改，请根据中文语言习惯意译，无需直译

2021-04-19 01:34 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
> +在以下的流程中，我们会构建并部署一个 NodeJs 的示例 app 。该 app 的源文件在[这里](https://github.com/oam-dev/kubevela/tree/master/docs/examples/testapp)。
英文单词和标点符号之间无需加空格

2021-04-19 01:34 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
> +### 2. 命令部署 app
使用命令部署 app

2021-04-19 01:34 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
> +在目录中，有一个符合 Appfile 格式的被 Vela 使用的 [vela.yaml](https://github.com/oam-dev/kubevela/tree/master/docs/examples/testapp/vela.yaml) 文件
这句话不太通顺，请根据中文语言习惯意译，无需直译

2021-04-19 01:34 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
> +> 注意：为了你可以推送镜像，请修改 `oamdev` 成你自己注册的账号。或者你可以尝试 `无需推送镜像到远程仓库的本地测试方式` 章节中的方式。
同上，无需直译

2021-04-19 01:34 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/developers/learn-appfile.md
>  Play more with your app:
更多关于 app 的操作：

2021-04-19 11:43 UTC, Casper-Mars commented
> 总体翻译流畅，有部分不通顺的地方请修改，请根据中文语言习惯意译，无需直译

好的，感谢支出

2021-04-21 00:52 UTC, sunny0826 approved these changes
LGTM

2021-04-21 00:52 UTC, merged