Translate i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
kubevela/kubevela.github.io pull request #47
Opened 2021-04-17 13:37 UTC by leason00

Translate i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md

2021-04-19 01:52 UTC, sunny0826 requested changes
翻译流畅，修改一下格式即可

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +可以通过简单地参考现有的 Kubernetes API资源来定义 KubeVela 中的 Trait。
英文和中文之间请加空格

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +让我们将此 Trait 附加到 `Application` 中的组件实例：
component 这里不用翻译

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +注意在这个例子中， 所引用资源的 `spec` 中的所有字段都将向最终用户公开，并且不允许将任何元数据（例如 `annotations` 等）设置为 Trait 的属性。 因此，当你希望将自己的CRD和控制器作为 Trait 时，通常使用此方法，并且它不依赖 `annotations` 等作为调整手段。
同上，注意英文和中文间的空格

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +也推荐使用 CUE 的方式来定义 Trait。 在这个例子中， 它带有抽象，你可以完全灵活地根据需要来模板化任何资源和字段。请注意，KubeVela要求所有 Trait 必须在CUE模板的 `outputs` 部分（而非 `output` ）中定义，格式如下：
同上

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +让我们将此 Trait 附加到`Application`中的组件实例中：
component 这里不用翻译

2021-04-19 01:52 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +基于CUE的 Trait 定义还可以支持许多其他高级方案，例如修补和数据传递。 在接下来的文档中将对它们进行详细说明。
英文和中文之间加空格，中文和标点符号之间不用

2021-04-19 14:30 UTC, Ghostbaby commented on i18n/zh/docusaurus-plugin-content-docs/current/cue/trait.md
> +可以通过简单地参考现有的 Kubernetes API资源来定义 KubeVela 中的 Trait。
可以通过简单地参考现有的 Kubernetes API 资源来定义 KubeVela 中的 Trait。

2021-04-22 11:50 UTC, leason00 commented
> 翻译流畅，修改一下格式即可

done

2021-04-23 00:46 UTC, Ghostbaby approved these changes
lgtm

2021-04-23 07:45 UTC, wonderflow approved these changes

2021-04-23 07:45 UTC, merged