Update install.mdx
kubevela/kubevela.github.io pull request #495
Opened 2022-02-07 09:11 UTC by workman-Lu

Distinguish between different versions of commands

2022-02-07 09:26 UTC, barnettZQG commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.2/install.mdx
> +kubectl create vela-system
kubectl create namespace vela-system

2022-02-08 02:03 UTC, barnettZQG commented
@workman-Lu Thanks!  Please change the English doc: https://github.com/oam-dev/kubevela.io/blob/main/docs/install.mdx

2022-02-08 02:56 UTC, msftgits commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495) before we can accept your contribution.<br/><br/>:x: workman-Lu [sign now](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/kubevela.io?pullRequest=495) it.</sub>

2022-02-08 03:32 UTC, msftgits commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495) before we can accept your contribution.<br/><br/>:x: workman-Lu [sign now](https://cla.opensource.microsoft.com/oam-dev/kubevela.io?pullRequest=495)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/oam-dev/kubevela.io?pullRequest=495) it.</sub>

2022-02-08 05:13 UTC, workman-Lu commented on i18n/zh/docusaurus-plugin-content-docs/version-v1.2/install.mdx
> +kubectl create vela-system
> kubectl create namespace vela-system

Already added

2022-02-08 05:23 UTC, wonderflow requested changes
I'm sorry I don't think we should add so many commands just for notice user the helm version.

We should list the helm version that should be `>= v3.2.0` in the requirements

2022-02-08 05:42 UTC, workman-Lu commented
> I'm sorry I don't think we should add so many commands just for notice user the helm version.
> 
> We should list the helm version that should be `>= v3.2.0` in the requirements

excellent idea

2022-02-08 05:43 UTC, wonderflow approved these changes
Cool

2022-02-08 06:42 UTC, merged