Feat: upgrade version to 1.2.3
kubevela/kubevela.github.io pull request #500
Opened 2022-02-09 03:39 UTC by barnettZQG

Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

2022-02-09 03:40 UTC, wonderflow requested changes
hold until we release

2022-02-09 03:41 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/install.mdx
> +```
We're should print the expected output

2022-02-10 03:58 UTC, wonderflow approved these changes

2022-02-10 04:00 UTC, wonderflow commented on docs/install.mdx
> +<details> <summary> check out the outcome </summary>
要把结果贴出来

2022-02-10 04:03 UTC, barnettZQG commented on docs/install.mdx
> +<details> <summary> check out the outcome </summary>
贴出来了呀。

2022-02-10 06:57 UTC, merged