Translate i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
kubevela/kubevela.github.io pull request #52
Opened 2021-04-20 14:31 UTC by zhujun74

尝试第一步工作，看看能行不。

2021-04-21 01:10 UTC, sunny0826 requested changes
有部分内容没有翻译，请完成翻译并确定格式正确，https://deploy-preview-52--condescending-montalcini-0d2353.netlify.app/zh/docs/next/helm/trait 这个是预览地址，可以自己先 review 一下

2021-04-21 01:10 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +在以下应用实例中，我们将基于Helm组件添加两个特性[scaler]和[virtualgroup.
你可以在预览链接里找到你翻译的文档，先 review 一下，这里请遵循 markdown 文件的格式，链接的括号要使用英文括号

2021-04-21 03:06 UTC, zhujun74 reviewed
容后续更新

2021-04-23 02:22 UTC, zhujun74 commented
已转分支zhujun74:zhujun74-patch-2 继续

2021-04-23 02:22 UTC, closed without merging