Translate i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
kubevela/kubevela.github.io pull request #53
Opened 2021-04-21 03:08 UTC by zhujun74

已更新状态，请确认

2021-04-21 03:27 UTC, zhujun74 reviewed
检查一下格式看看能否通过review

2021-04-21 04:17 UTC, zhujun74 commented
> 检查一下格式看看能否通过review

2021-04-21 04:45 UTC, zhujun74 commented
更新状态

2021-04-23 01:10 UTC, Ghostbaby reviewed
comment left

2021-04-23 01:10 UTC, Ghostbaby commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +KubeVela中的特性可以从基于Helm的组件无缝添加.
```suggestion
KubeVela 中的特性可以从基于 Helm 的组件无缝添加.
```
请在中英文中间添加空格，以下相同错误就不一一指出了。

2021-04-23 01:10 UTC, Ghostbaby commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +> 注意: 当我们使用基于Helm的特性时, please *请确认在你Helm图标中的目标负载严格按照qualified-full-name convention in Helm的命名方式.* [以此表为例](https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8f5b335/charts
```suggestion
> 注意: 当我们使用基于 Helm 的特性时,  *请确认在你 Helm chart 中的目标工作负载严格按照完全合规的命名方式.* [以此 chart 为例](https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8f5b335/charts/podinfo/templates/deployment.yaml#L4), 这个工作负载名由[版本名和 chart 名]组成(https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8f5b335/charts/podinfo/templates/_helpers.tpl#L13).
```

2021-04-23 01:10 UTC, Ghostbaby commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +检查缩放组 `scaler` 特性生效.
```suggestion
检查  `scaler` 特性生效。
``

2021-04-23 07:46 UTC, wonderflow commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +标题:  添加特性
Trait 是概念词汇，不用翻译

2021-04-27 01:33 UTC, sunny0826 requested changes
翻译完请先review一下，这里开启了预览模式，可以先预览自己翻译的内容

2021-04-27 01:33 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +(https://github.com/oam-dev/kubevela/blob/master/docs/examples/helm-module/virtual-group-td.yaml)
翻译完，请先review一些，这里的连接地址都不对
https://deploy-preview-53--kubevela.netlify.app/zh/docs/next/helm/trait

2021-04-27 01:33 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +> 注意: 当我们使用基于 Helm 的 Trait 特性时, please *请确认在你 Helm 图标中的目标负载严格按照 qualified-full-name convention in Helm 的命名方式.* [以此表为例](https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8
同上

2021-04-27 23:35 UTC, zhujun74 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +(https://github.com/oam-dev/kubevela/blob/master/docs/examples/helm-module/virtual-group-td.yaml)
好的

2021-04-28 00:52 UTC, zhujun74 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +> 注意: 当我们使用基于 Helm 的 Trait 特性时, please *请确认在你 Helm 图标中的目标负载严格按照 qualified-full-name convention in Helm 的命名方式.* [以此表为例](https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8
那个预览review旁边的 outdated 是啥意思？

2021-04-28 00:57 UTC, zhujun74 reviewed
已review #53

2021-04-28 01:00 UTC, zhujun74 reviewed
@wonderflow  #53  OK

2021-04-28 02:21 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +> 注意: 当我们使用基于 Helm 的 Trait 特性时, please *请确认在你 Helm 图标中的目标负载严格按照 qualified-full-name convention in Helm 的命名方式.* [以此表为例](https://github.com/captainroy-hy/podinfo/blob/c2b9603036f1f033ec2534ca0edee8eff8
这里 review 不太明确，应该是 preview，是点开上面的连接，找到翻译的文章，检查格式，请遵循 markdown 的格式，连接的格式应该是 `[连接文字](连接地址)`

2021-04-28 03:16 UTC, sunny0826 requested changes
前面的链接修复了就可以合并了

2021-04-28 03:16 UTC, sunny0826 commented on i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md
> +(https://github.com/oam-dev/kubevela/blob/master/docs/examples/helm-module/virtual-group-td.yaml)
这里的连接也需要修改

2021-04-28 03:18 UTC, sunny0826 commented
修复完成后，请先在下面这个预览页面查看一下修复效果
https://deploy-preview-53--kubevela.netlify.app/zh/docs/next/helm/trait/

2021-04-28 04:01 UTC, zhujun74 commented
经过链接浏览网页，感觉整体尚可，请予以合并分支！谢谢杰克朱祝您健康快乐！-------- 原始邮件 --------主题：Re: [oam-dev/kubevela.io] Translate i18n/zh/docusaurus-plugin-content-docs/current/helm/trait.md  (#53)发件人：guoxudong 收件人："oam-dev/kubevela.io" 抄送：Jackzhu ,Comment 

修复完成后，请先在下面这个预览页面查看一下修复效果

https://deploy-preview-53--kubevela.netlify.app/zh/docs/next/helm/trait/



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/oam-dev/kubevela.io/pull/53#issuecomment-828111271",

"url": "https://github.com/oam-dev/kubevela.io/pull/53#issuecomment-828111271",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

2021-04-28 04:05 UTC, zhujun74 commented
已完成在下面这个预览页面查看修复效果
https://deploy-preview-53--kubevela.netlify.app/zh/docs/next/helm/trait/

2021-04-28 04:25 UTC, sunny0826 commented
![image](https://user-images.githubusercontent.com/24563928/116346402-c6099700-a81c-11eb-8871-0d8bef365bc4.png)
![image](https://user-images.githubusercontent.com/24563928/116346410-cb66e180-a81c-11eb-91e8-dc01125504c3.png)
这两处的连接显示是有问题的

2021-04-28 05:06 UTC, sunny0826 approved these changes
lgtm

2021-04-28 05:06 UTC, merged

2021-04-28 05:07 UTC, zhujun74 commented
THX