doc: translate of build addon registry
kubevela/kubevela.github.io pull request #871
Opened 2022-07-22 14:53 UTC by cezhang

#814
Signed-off-by: cezhang <c1zhang.dev@gmail.com>

2022-07-22 15:00 UTC, charlie0129 commented
Sorry but the file inside `zh` is not up-to-date. Would you please check https://kubevela.net/docs/next/platform-engineers/addon/addon-registry for the latest version and base your translations on that?

2022-07-22 15:28 UTC, cezhang commented
> Sorry but the file inside `zh` is not up-to-date [#814 (comment)](https://github.com/kubevela/kubevela.io/issues/814#issuecomment-1190631802) . Would you please check https://kubevela.net/docs/next/platform-engineers/addon/addon-registry for the latest version and base your translations on that?

OMG, my bad.

2022-07-24 06:42 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +## 构建和推送到定制的 Helm Chart 仓库
```suggestion
## 构建和推送到自建的 Helm Chart 仓库
```

2022-07-24 06:44 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +[Helm chart 仓库](https://helm.sh/docs/topics/chart_repository/) 可以用来存储打包的插件。 [ChartMuseum](https://chartmuseum.com/) 是一个开源的容易部署的 Helm Chart 仓库服务器。
```suggestion
[Helm chart 仓库](https://helm.sh/docs/topics/chart_repository/) 可以用来存储插件，并带有版本管理。 [ChartMuseum](https://chartmuseum.com/) 是一个开源的容易部署的 Helm Chart 仓库服务器。  
```

2022-07-24 06:45 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +在这个教程中，我们将使用 [ChartMuseum](https://chartmuseum.com/) 来构建我们的仓库。假如你已经有这样一个仓库，不用担心。 你依然可以遵循以下步骤，除了你不能使用 `vela addon push` 命令和需要手动更新你的插件。
```suggestion
在这个教程中，我们将使用 [ChartMuseum](https://chartmuseum.com/) 来构建我们的仓库。假如你已经有这样一个仓库，不用担心，除了你不能使用 `vela addon push` 命令和需要手动更新你的插件， 你依然可以遵循以下步骤。  
```

2022-07-24 06:46 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +请注意：你也可以使用兼容 ChartMuseum 的 registry, 例如（ Harbor ）。 他们都具体同样的功能。
```suggestion
请注意：你也可以使用兼容 ChartMuseum 的 registry （例如 Harbor ），它们都具体同样的功能。
```

2022-07-24 06:48 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +KubeVela已经有相应的 ChartMuseum 插件。 你可以创建你自己的 ChartMuseum 实例或者使用 KubeVela 的插件。 要使用它，运行：
```suggestion
KubeVela 已经提供了 ChartMuseum 插件，你可以手动创建你自己的 ChartMuseum 实例或者使用 KubeVela 的插件。 要使用该插件，运行：
```

2022-07-24 06:48 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +> 要自定义插件的参数, 可以:
```suggestion
> 如果要自定义插件的参数，任选其一:
```

2022-07-24 06:49 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +> - 使用 VelaUX 和 当要安装插件时填写相应的参数表格
```suggestion
> - 使用 VelaUX 并且在启用插件时填写相应的参数
```

2022-07-24 06:50 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +> - 或者查看通过命令 `vela addon status chartmuseum -v` 查看可用的参数，和通过命令 `vela addon enable chartmuseum externalPort=80` 来指定相应的参数。
```suggestion
> - 或者查看通过命令 `vela addon status chartmuseum -v` 查看可用的参数，并通过命令 `vela addon enable chartmuseum externalPort=80` 来指定相应的参数。
```

2022-07-24 06:51 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +在成功安装插件之后，我们必须保证可以通过默认的端口转发（8080）的方式访问 ChartMuseum 。
```suggestion
在成功安装插件之后，为了保证你能够访问 ChartMuseum ，我们将转发默认端口（8080）：
```

2022-07-24 06:51 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +> 通常，你可能需要配置 ingress（可以通过插件的参数来实现）来实现外界的访问。
```suggestion
> 一般来说，你可能需要配置 ingress（可以通过插件的参数来实现）来实现外界的访问。 
```

2022-07-24 06:52 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +使用你刚刚创建的 ChartMuseum 仓库（或者其他  Helm Chart 仓库 ）作为插件 registry。 我们将其命名为 `localcm` :
```suggestion
使用你刚刚创建的 ChartMuseum 仓库（或者其他  Helm Chart 仓库 ）作为插件 registry ，我们将其命名为 `localcm` :
```

2022-07-24 06:52 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 假如需要提供用户名和密码，你可以用 --username and --password 来分别指定它
```suggestion
# 假如需要提供用户名和密码，你可以用 --username 和 --password 来分别指定它们
```

2022-07-24 06:53 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +你现在可以在列表中看到：
```suggestion
你现在可以在列表中看到自建仓库了：
```

2022-07-24 06:54 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +> 可以略过这一步。 假如你不想手动打包插件，我们可以为你完成这一步骤。
```suggestion
> 你可以略过这一步。 假如你不想手动打包插件，我们将会自动为你完成这一步骤。
```

2022-07-24 06:56 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 假如你自己打包，仅仅替换 `sample-addon` 为 `sample-addon-1.0.0.tgz`
```suggestion
# 假如你自己打包了，只需替换 `sample-addon` 为 `sample-addon-1.0.0.tgz`
```

2022-07-24 06:57 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 除了 registry 名（localcm， 就像我们之前创建的时候一样）， URLs 也同样支持。
```suggestion
# 除了 registry 名（见上 localcm ）， URL 也同样支持。
```

2022-07-24 06:57 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 假如你使用 URLs， 你甚至不需要将它添加为 addon registry。
```suggestion
# 假如你使用 URL， 你甚至不需要将它添加为 addon registry。 
```

2022-07-24 06:58 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 这是因为我们之前已经推送了相同插件到 registry。
```suggestion
# 这是因为我们之前已经推送了相同的插件到同一个 registry。
```

2022-07-24 06:59 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +现在registry 里面已经有你可用的插件了！
```suggestion
现在 registry 里面已经有你的插件了！
```

2022-07-24 07:00 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +## 同步插件到 air-gapped 环境的 ChartMuseum
```suggestion
## 在离线环境中同步插件到 ChartMuseum
```

2022-07-24 07:03 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +就像 [*Air-gapped Installation for Addon*](../system-operation/enable-addon-offline) 里描述的，你可以从本地的文件系统安装插件。但是有些插件需要 Helm Chart 的形式，你需要为此构建 Chart 仓库。这部分内容将解决这一问题。你也可以从 [addon catalog](https://github.com/
```suggestion
就像 [*插件的离线安装*](../system-operation/enable-addon-offline) 里描述的，你可以从本地文件系统安装插件。但是有些插件中需要 Helm Chart ，那么你将需要为此构建 Chart 仓库，这部分内容将解决这一问题。你也可以学习到如何从 [addon catalog](https://github.com/kubevela/catalog) 同步插件到自建的 ChartMuseum 实例上，这样你可以直接从 registry 安装插件，而不用从本地文件系统来安装。
```

2022-07-24 07:03 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +- ChartMuseum 插件的 Air-gapped 安装
```suggestion
- ChartMuseum 插件的离线安装
```

2022-07-24 07:04 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +- 同步插件目录到你的 ChartMuseum 实例
```suggestion
- 同步 addon catalog 到你的 ChartMuseum 实例
```

2022-07-24 07:04 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +- 同步 Helm Charts 到你的 ChartMuseum 实例
```suggestion
- 同步 Helm Chart 到你的 ChartMuseum 实例
```

2022-07-24 07:04 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +### ChartMuseum 插件的 Air-gapped 安装
```suggestion
### ChartMuseum 插件的离线安装
```

2022-07-24 07:05 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +因为安装 ChartMuseum 插件的所有文件存储在 catalog 中，你需要先从 [addon catalog](https://github.com/kubevela/catalog) 下载：
```suggestion
因为安装 ChartMuseum 插件的所需文件存储在 catalog 中，你需要先从 [addon catalog](https://github.com/kubevela/catalog) 下载：
```

2022-07-24 07:07 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +现在你需要同步 ChartMuseum 镜像到你的集群。例如，你可以预加载原始的镜像到你到集群中或者同步镜像到你的私有镜像 registry然后使用自定义的镜像。
```suggestion
现在你需要想方设法同步 ChartMuseum 镜像到你的集群。例如，你可以预加载 ChartMuseum 镜像到你到集群中，或者同步 ChartMuseum 镜像到你的私有镜像仓库然后在插件中使用自定义镜像。
```

2022-07-24 07:08 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +为了弄清楚 ChartMuseum 正在使用的默认镜像：
```suggestion
你可以这样找出 ChartMuseum 正在使用的默认镜像：
```

2022-07-24 07:08 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 下载这个镜像到你的私有集群中。
```suggestion
# 你需要下载这个镜像并同步到你的私有集群中。
```

2022-07-24 07:09 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +现在 ChartMuseum 插件应该已经安装了。
```suggestion
现在 ChartMuseum 插件应该已经启用了。
```

2022-07-24 07:09 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +### 同步插件目录到你的 ChartMuseum 实例
```suggestion
### 同步 addon catalog 到你的 ChartMuseum 实例
```

2022-07-24 07:10 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +在你继续之前，你必须保证你可以访问你的 ChartMuseum 实例。查看之前关于如何使用插件 registry 的部分。我们假设你使用之前部分描述的相同配置（例如，你可以正常访问名为 `localcm` 的实例）。
```suggestion
在你继续之前，你必须保证你可以访问你的 ChartMuseum 实例。查看之前关于如何使用 ChartMuseum 作为插件 registry 的章节。我们假设你使用与之前部分的相同配置（也就是说，你可以正常访问名为 `localcm` 的实例）。
```

2022-07-24 07:12 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +在你刚刚克隆的仓库里，移动到 `catalog/addons`。 你应该可以看到社区验证过的一系列插件。
```suggestion
在你刚刚克隆的仓库里，移动到 `catalog/addons`。 你应该可以看到一系列社区认证的插件。  
```

2022-07-24 07:13 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +你可以同步所有在 catalog 里面的插件到你的 ChartMuseum 实例和在你的私有环境里使用他们。我们可以使用命令 `vela addon push` 打包这些插件并同步到 ChartMuseum 中。
```suggestion
你可以同步所有在 catalog 里面的插件到你的 ChartMuseum 实例并在你的私有环境里使用他们。我们将利用 `vela addon push` 打包这些插件并同步到 ChartMuseum 中。  
```

2022-07-24 07:14 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +据我们知道，我们可以使用以下命令推送单个插件到 ChartMuseum：
```suggestion
众所周知，我们可以使用以下命令推送单个插件到 ChartMuseum：
```

2022-07-24 07:15 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +Therefore, we can use a loop to push all addons to ChartMuseum:
```suggestion
那么，我们可以利用一个循环来推送所有的插件到 ChartMuseum：
```

2022-07-24 07:15 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 你的 PWD 应为 catalog/addons
```suggestion
# 你的当前工作目录应为 catalog/addons
```

2022-07-24 07:16 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 将你自己的 registry 名替换 `localcm`。
```suggestion
# 将 `localcm` 替换为你自己的 registry 名称
```

2022-07-24 07:17 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +恭喜，现在所有社区验证的插件都可以在你的 ChartMuseum 实例中使用了（用命令 `vela addon list` 来查看，和使用命令 `vela addon enable addon-name` 来安装它们。同样你可以以同样的方来使用 `experimental` 的插件。
```suggestion
恭喜，现在所有社区认证的插件都可以在你的 ChartMuseum 实例中使用了（用命令 `vela addon list` 来查看，并使用命令 `vela addon enable addon-name` 来安装它们）。同样地，你可以类似的方法来同步 `experimental` 的插件。
```

2022-07-24 07:18 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +当你需要安装 Helm Chart 形式的插件而你不能直接访问 Chart 的时候，这个特别有用。
```suggestion
当你需要安装内部使用了 Helm Chart 的插件，而你不能直接访问使用的 Chart 的时候，这个特别有用。  
```

2022-07-24 07:19 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +我们这里将以 `dex` 插件为例。这个插件是从 `dexidp` 使用名为 `dex` 的 Chart。 我们可以将这个 Chart 导入到我们的 ChartMuseum 的实例并修改 `dex` 插件来使用我们自定义的 Chart。
```suggestion
我们这里将以 `dex` 插件为例，这个插件从 `dexidp` 中使用了名为 `dex` 的 Chart。 我们可以将这个 Chart 导入到我们的 ChartMuseum 的实例并修改 `dex` 插件来使用我们自己导入的 Chart。  
```

2022-07-24 07:20 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# 假如你有安装好的 Helm 插件， 也可以使用 helm cm-push
```suggestion
# 假如你的 helm 安装好了 cm-push 插件， 也可以使用 helm cm-push
```

2022-07-24 07:21 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +现在你的 ChartMuseum 实例中已经有 `dex` 了。 是时候取使用它。
```suggestion
现在你的 ChartMuseum 实例中已经有 `dex` 了。 是时候取使用它了：
```

2022-07-24 07:21 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +        # Put your ChartMuseum URL here
```suggestion
        # 把你的 ChartMuseum URL 填入这里
```

2022-07-24 07:22 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +# template.yaml of dex addon
```suggestion
# dex addon 的 template.yaml
```

2022-07-24 07:23 UTC, charlie0129 commented on i18n/zh/docusaurus-plugin-content-docs/current/platform-engineers/addon/addon-registry.md
> +很好！在你安装插件之后，它旧尝试从你的 ChartMuseum 实例中拉取相应的 Chart 了。（你也可以考虑将 Chart 中的镜像变得本地可用）。
```suggestion
很好！在你安装 `dex` 插件时，它将尝试从你的 ChartMuseum 实例中拉取相应的 Chart 。（当然，你也应该使 Chart 中的镜像在你的私有集群中可用）
```

2022-07-24 07:28 UTC, charlie0129 requested changes
Good job. Thanks for your contribution. 

But please note: 如果使用机翻请一定通读一遍保持语句通顺，在中文中使用英文语序是难以阅读的；同时请不要遗漏原文内容；英语跟中文的表达方式有较大差异，不能生搬硬套，可用适当意译来更好地表达原文意思。

2022-08-02 05:41 UTC, wonderflow approved these changes
thanks

2022-08-02 05:41 UTC, merged